a = int(input("Enter a number: "))  
b = int(input("Enter another number: "))
c = input("Enter a string: ")
print("You First Number is:", a)
print("You Second Number is:", b)
print("You String is:", c)